import {StyleSheet} from 'react-native';
import {PixelRatio, Width, Height} from 'configs/size';

export default styles = StyleSheet.create({
  container: {
    width: 440 * PixelRatio,
    marginLeft: 20 * PixelRatio,
    height: 600 * PixelRatio,

    marginTop: 150 * PixelRatio,
    borderWidth: 1 * PixelRatio,
    borderRadius: 5 * PixelRatio,
    backgroundColor: 'rgb(244,244,244)',
    elevation: 5 * PixelRatio,
  },
  board: {
    width: 420 * PixelRatio,
    height: 420 * PixelRatio,
    margin: 10 * PixelRatio,
  },
  user_view: {
    width: '100%',
    alignItems: 'center',
  },
  user_text: {
    fontSize: 20 * PixelRatio,
  },
  dot11: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 40 * PixelRatio,
    marginLeft: 40 * PixelRatio,
    position: 'absolute',
  },
  dot12: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 40 * PixelRatio,
    marginLeft: 80 * PixelRatio,
    position: 'absolute',
  },
  dot13: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 40 * PixelRatio,
    marginLeft: 120 * PixelRatio,
    position: 'absolute',
  },
  dot14: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 40 * PixelRatio,
    marginLeft: 160 * PixelRatio,
    position: 'absolute',
  },
  dot15: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 40 * PixelRatio,
    marginLeft: 200 * PixelRatio,
    position: 'absolute',
  },
  dot16: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 40 * PixelRatio,
    marginLeft: 242 * PixelRatio,
    position: 'absolute',
  },
  dot17: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 40 * PixelRatio,
    marginLeft: 285 * PixelRatio,
    position: 'absolute',
  },
  dot18: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 40 * PixelRatio,
    marginLeft: 325 * PixelRatio,
    position: 'absolute',
  },
  dot19: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 40 * PixelRatio,
    marginLeft: 365 * PixelRatio,
    position: 'absolute',
  },
  dot21: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 80 * PixelRatio,
    marginLeft: 40 * PixelRatio,
    position: 'absolute',
  },
  dot22: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,

    marginTop: 80 * PixelRatio,
    marginLeft: 80 * PixelRatio,
    position: 'absolute',
  },
  dot23: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,

    marginTop: 80 * PixelRatio,
    marginLeft: 120 * PixelRatio,
    position: 'absolute',
  },
  dot24: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,

    marginTop: 80 * PixelRatio,
    marginLeft: 160 * PixelRatio,
    position: 'absolute',
  },
  dot25: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,

    marginTop: 80 * PixelRatio,
    marginLeft: 200 * PixelRatio,
    position: 'absolute',
  },
  dot26: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,

    marginTop: 80 * PixelRatio,
    marginLeft: 242 * PixelRatio,
    position: 'absolute',
  },
  dot27: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,

    marginTop: 80 * PixelRatio,
    marginLeft: 285 * PixelRatio,
    position: 'absolute',
  },
  dot28: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,

    marginTop: 80 * PixelRatio,
    marginLeft: 325 * PixelRatio,
    position: 'absolute',
  },
  dot29: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,

    marginTop: 80 * PixelRatio,
    marginLeft: 365 * PixelRatio,
    position: 'absolute',
  },
  dot31: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,

    marginTop: 120 * PixelRatio,
    marginLeft: 40 * PixelRatio,
    position: 'absolute',
  },
  dot32: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,

    marginTop: 120 * PixelRatio,
    marginLeft: 80 * PixelRatio,
    position: 'absolute',
  },
  dot33: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,

    marginTop: 120 * PixelRatio,

    marginLeft: 120 * PixelRatio,
    position: 'absolute',
  },
  dot34: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,

    marginTop: 120 * PixelRatio,
    marginLeft: 160 * PixelRatio,
    position: 'absolute',
  },
  dot35: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 120 * PixelRatio,
    marginLeft: 200 * PixelRatio,
    position: 'absolute',
  },
  dot36: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 120 * PixelRatio,
    marginLeft: 242 * PixelRatio,
    position: 'absolute',
  },
  dot37: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 120 * PixelRatio,
    marginLeft: 285 * PixelRatio,
    position: 'absolute',
  },
  dot38: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 120 * PixelRatio,
    marginLeft: 325 * PixelRatio,
    position: 'absolute',
  },
  dot39: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 120 * PixelRatio,
    marginLeft: 365 * PixelRatio,
    position: 'absolute',
  },
  dot41: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 160 * PixelRatio,
    marginLeft: 40 * PixelRatio,
    position: 'absolute',
  },
  dot42: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 160 * PixelRatio,
    marginLeft: 80 * PixelRatio,
    position: 'absolute',
  },
  dot43: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 160 * PixelRatio,
    marginLeft: 120 * PixelRatio,
    position: 'absolute',
  },
  dot44: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 160 * PixelRatio,
    marginLeft: 160 * PixelRatio,
    position: 'absolute',
  },
  dot45: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 160 * PixelRatio,
    marginLeft: 200 * PixelRatio,
    position: 'absolute',
  },
  dot46: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 160 * PixelRatio,
    marginLeft: 242 * PixelRatio,
    position: 'absolute',
  },
  dot47: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 160 * PixelRatio,
    marginLeft: 285 * PixelRatio,
    position: 'absolute',
  },
  dot48: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 160 * PixelRatio,
    marginLeft: 325 * PixelRatio,
    position: 'absolute',
  },
  dot49: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 160 * PixelRatio,
    marginLeft: 365 * PixelRatio,
    position: 'absolute',
  },
  dot51: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 200 * PixelRatio,
    marginLeft: 40 * PixelRatio,
    position: 'absolute',
  },
  dot52: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 200 * PixelRatio,
    marginLeft: 80 * PixelRatio,
    position: 'absolute',
  },
  dot53: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 200 * PixelRatio,
    marginLeft: 120 * PixelRatio,
    position: 'absolute',
  },
  dot54: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 200 * PixelRatio,
    marginLeft: 160 * PixelRatio,
    position: 'absolute',
  },
  dot55: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 200 * PixelRatio,
    marginLeft: 200 * PixelRatio,
    position: 'absolute',
  },
  dot56: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 200 * PixelRatio,
    marginLeft: 242 * PixelRatio,
    position: 'absolute',
  },
  dot57: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 200 * PixelRatio,
    marginLeft: 285 * PixelRatio,
    position: 'absolute',
  },
  dot58: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 200 * PixelRatio,
    marginLeft: 325 * PixelRatio,
    position: 'absolute',
  },
  dot59: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 200 * PixelRatio,
    marginLeft: 365 * PixelRatio,
    position: 'absolute',
  },
  dot61: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 243 * PixelRatio,
    marginLeft: 40 * PixelRatio,
    position: 'absolute',
  },
  dot62: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 243 * PixelRatio,
    marginLeft: 80 * PixelRatio,
    position: 'absolute',
  },
  dot63: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 243 * PixelRatio,
    marginLeft: 120 * PixelRatio,
    position: 'absolute',
  },
  dot64: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 243 * PixelRatio,
    marginLeft: 160 * PixelRatio,
    position: 'absolute',
  },
  dot65: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 243 * PixelRatio,
    marginLeft: 200 * PixelRatio,
    position: 'absolute',
  },
  dot66: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 243 * PixelRatio,
    marginLeft: 242 * PixelRatio,
    position: 'absolute',
  },
  dot67: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 243 * PixelRatio,
    marginLeft: 285 * PixelRatio,
    position: 'absolute',
  },
  dot68: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 243 * PixelRatio,
    marginLeft: 325 * PixelRatio,
    position: 'absolute',
  },
  dot69: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 243 * PixelRatio,
    marginLeft: 365 * PixelRatio,
    position: 'absolute',
  },
  dot71: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 285 * PixelRatio,
    marginLeft: 40 * PixelRatio,
    position: 'absolute',
  },
  dot72: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 285 * PixelRatio,
    marginLeft: 80 * PixelRatio,
    position: 'absolute',
  },
  dot73: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 285 * PixelRatio,
    marginLeft: 120 * PixelRatio,
    position: 'absolute',
  },
  dot74: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 285 * PixelRatio,
    marginLeft: 160 * PixelRatio,
    position: 'absolute',
  },
  dot75: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 285 * PixelRatio,
    marginLeft: 200 * PixelRatio,
    position: 'absolute',
  },
  dot76: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 285 * PixelRatio,
    marginLeft: 242 * PixelRatio,
    position: 'absolute',
  },
  dot77: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 285 * PixelRatio,
    marginLeft: 285 * PixelRatio,
    position: 'absolute',
  },
  dot78: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 285 * PixelRatio,
    marginLeft: 325 * PixelRatio,
    position: 'absolute',
  },
  dot79: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 285 * PixelRatio,
    marginLeft: 365 * PixelRatio,
    position: 'absolute',
  },
  dot81: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 328 * PixelRatio,
    marginLeft: 40 * PixelRatio,
    position: 'absolute',
  },
  dot82: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 328 * PixelRatio,
    marginLeft: 80 * PixelRatio,
    position: 'absolute',
  },
  dot83: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 328 * PixelRatio,
    marginLeft: 120 * PixelRatio,
    position: 'absolute',
  },
  dot84: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 328 * PixelRatio,
    marginLeft: 160 * PixelRatio,
    position: 'absolute',
  },
  dot85: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 328 * PixelRatio,
    marginLeft: 200 * PixelRatio,
    position: 'absolute',
  },
  dot86: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 328 * PixelRatio,
    marginLeft: 242 * PixelRatio,
    position: 'absolute',
  },
  dot87: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 328 * PixelRatio,
    marginLeft: 285 * PixelRatio,
    position: 'absolute',
  },
  dot88: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 328 * PixelRatio,
    marginLeft: 325 * PixelRatio,
    position: 'absolute',
  },
  dot89: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 328 * PixelRatio,
    marginLeft: 365 * PixelRatio,
    position: 'absolute',
  },
  dot91: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 365 * PixelRatio,
    marginLeft: 40 * PixelRatio,
    position: 'absolute',
  },
  dot92: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 365 * PixelRatio,
    marginLeft: 80 * PixelRatio,
    position: 'absolute',
  },
  dot93: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 365 * PixelRatio,
    marginLeft: 120 * PixelRatio,
    position: 'absolute',
  },
  dot94: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 365 * PixelRatio,
    marginLeft: 160 * PixelRatio,
    position: 'absolute',
  },
  dot95: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 365 * PixelRatio,
    marginLeft: 200 * PixelRatio,
    position: 'absolute',
  },
  dot96: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 365 * PixelRatio,
    marginLeft: 242 * PixelRatio,
    position: 'absolute',
  },
  dot97: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 365 * PixelRatio,
    marginLeft: 285 * PixelRatio,
    position: 'absolute',
  },
  dot98: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 365 * PixelRatio,
    marginLeft: 325 * PixelRatio,
    position: 'absolute',
  },
  dot99: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    marginTop: 365 * PixelRatio,
    marginLeft: 365 * PixelRatio,
    position: 'absolute',
  },
  go_white: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    backgroundColor: 'white',
    borderRadius: 45 * PixelRatio,
  },
  go_black: {
    width: 25 * PixelRatio,
    height: 25 * PixelRatio,
    backgroundColor: 'black',
    borderRadius: 45 * PixelRatio,
  },
  line1: {
    borderWidth: 1,
  },
  caidan_view: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 40 * PixelRatio,
  },
  caidan_text: {
    fontSize: 22 * PixelRatio,
  },
});
